### PR TITLE
docs: Add cheqd-node 1.x.x version changes to the CLI

### PR DESCRIPTION
**Pull request by anikitinDSR**

### CODE REVIEW

**Comment by Tweeddalex** [comment]
Hey @anikitinDSR just going through this now - in your examples for the payload.json files, some of the fields are in Protobuf syntax (snake_case), others are different e.g. "SignInputs". Should these all not be consistently in Protobuf syntax?

**Comment by anikitinDSR** [comment]
>

**Comment by anikitinDSR** [comment]
> Hey @anikitinDSR just going through this now - in your examples for the payload.json files, some of the fields are in Protobuf syntax (snake_case), others are different e.g. "SignInputs". Should these all not be consistently in Protobuf syntax?

Hey! un fortunately we have not moved to using the same case for CLI payloads, output JSON and input JSON... Here I put exact format for payload JSON which cosmos-based CLI requires.

**Comment by Tweeddalex** [comment]
> > Hey @anikitinDSR just going through this now - in your examples for the payload.json files, some of the fields are in Protobuf syntax (snake_case), others are different e.g. "SignInputs". Should these all not be consistently in Protobuf syntax?
> 
> Hey! un fortunately we have not moved to using the same case for CLI payloads, output JSON and input JSON... Here I put exact format for payload JSON which cosmos-based CLI requires.

Ah okay cool, just checking it wasn't an error - happy to merge this then!

**Pull request merged**
